procgen: MainDriver.cpp Coord2D.hpp Tile.hpp Hash.hpp Path.hpp Grid2D.hpp GameGrid2D.hpp
	g++ -std=c++11 MainDriver.cpp Coord2D.hpp Tile.hpp Hash.hpp Path.hpp Grid2D.hpp GameGrid2D.hpp -o procgen

clean:
	rm -f *.o *.gch procgen